/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package metaverse_log_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author MD WASEEM AKRAM
 */
public class exitFill extends javax.swing.JFrame {

    /**
     * Creates new form exitFill
     */
    public exitFill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EntryTime = new javax.swing.JPanel();
        Alllogs = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ExitTime = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        i = new javax.swing.JLabel();
        IDExit = new javax.swing.JTextField();
        NameExit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DateExit = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        TimeExit = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        Submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EntryTime.setBackground(new java.awt.Color(102, 153, 255));
        EntryTime.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Alllogs.setText("All Logs");
        Alllogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlllogsActionPerformed(evt);
            }
        });
        EntryTime.add(Alllogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MENUS");
        EntryTime.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        ExitTime.setBackground(new java.awt.Color(255, 153, 102));
        ExitTime.setText("Exit Time");
        ExitTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitTimeActionPerformed(evt);
            }
        });
        EntryTime.add(ExitTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 120, -1));

        jButton2.setText("Entry Time");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        EntryTime.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, -1));

        getContentPane().add(EntryTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 200));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("User Exit Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        i.setText("ID");
        getContentPane().add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        IDExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDExitActionPerformed(evt);
            }
        });
        getContentPane().add(IDExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 160, -1));
        getContentPane().add(NameExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 190, -1));

        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jLabel4.setText("Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        DateExit.setEditable(false);
        DateExit.setText("No need to  add");
        getContentPane().add(DateExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 160, -1));

        jLabel5.setText("Time");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        TimeExit.setEditable(false);
        TimeExit.setText("no need to add");
        getContentPane().add(TimeExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 160, -1));

        jButton3.setBackground(new java.awt.Color(255, 0, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metaverse_log_system/icons8-cancel-24.png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 90, 40));

        Submit.setBackground(new java.awt.Color(255, 51, 51));
        Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metaverse_log_system/icons8-submit-document-32.png"))); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlllogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlllogsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new allLogs().setVisible(true);
    }//GEN-LAST:event_AlllogsActionPerformed

    private void ExitTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitTimeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new exitFill().setVisible(true);
    }//GEN-LAST:event_ExitTimeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new userFill().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void IDExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDExitActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new index().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        
         String id=IDExit.getText();
        String name=NameExit.getText();
       
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mls","root","Sohailsql@#@123");
            Statement st=con.createStatement();
            st.executeUpdate("update log set timeexit=current_time() where id='"+id+"'");
            st.executeUpdate("update log set dateexit=current_date() where id='"+id+"'");
             JOptionPane.showMessageDialog(null, "Data updated Successfully");
             setVisible(false);
             new userFill().setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, ""+e.toString()+"");
            
        }
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exitFill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exitFill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exitFill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exitFill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exitFill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alllogs;
    private javax.swing.JFormattedTextField DateExit;
    private javax.swing.JPanel EntryTime;
    private javax.swing.JButton ExitTime;
    private javax.swing.JTextField IDExit;
    private javax.swing.JTextField NameExit;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField TimeExit;
    private javax.swing.JLabel i;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
